image: maven:3.3.9-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache decompiled minecraft-server and Spigot-API artifacts
cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
  - "mvn $MAVEN_CLI_OPTS compile"

deploy:
  stage: deploy
  script:
  - "mvn $MAVEN_CLI_OPTS deploy"
  only:
  - master